$schema: "http://json-schema.org/draft-07/schema#"
description: config dictionary
type: object
properties:
    # Input data
    traits:
        type: string
        description: path to tsv file containining trait metadata
    variants:
        type: string
        description: path to vcf file
    plink_prefix:
        type: string
        description: plink file prefix

    # Data symlinking
    symlink_data:
        type: boolean
        default: true
        description: whether variant data should be symlinked
    symlink_dir:
        type: string
        default: data
        description: path to directory where variant data should be symlinked

    # SNP filtering
    snp_filtering:
        type: object
        properties:
            hwe_p:
                type: number
                minimum: 0
                maximum: 1
                default: 0.000001
                description: Hardy-Weinberg p-value threshold
            maf:
                type: number
                minimum: 0
                maximum: 0.5
                default: 0.05
                description: Minor allele frequency threshold

    # General PLINK parameters
    plink:
        allow_extra_chr:
            type: boolean
            default: false
            description: whether to allow non-standard chromosome names
        family_id_flags:
            type: string
            default: --double-id
            description: what method to use for setting family IDs

    # Cluster parameters
    cluster:
        type: object
        properties:
            cookiecutter_url:
                type: string
                default: null
                description: url or path to cookiecutter profile to use
            profile_name:
                type: string
                description: name of the profile
            use-conda:
                type: boolean
                description: whether or not to use conda for managing software dependencies
            restart-times:
                type: integer
                minimum: 0
                description: how many times snakemake tries to restart failing jobs
            jobs:
                type: integer
                minimum: 1
                description: maximum number of concurrent jobs to submit to submit to the cluster
            latency-wait:
                type: integer
                minimum: 0
                description: maximum time (in seconds) that snakemake waits for missing output files
        dependencies:
            cookiecutter_url:
                - profile_name
                - use-conda
                - restart-times
                - jobs
                - latency-wait

required:
    - traits
    - variants
